package: seoinspector
version: '0.5'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/seoinspector

requires:
    redaxo: '>=5.12.0'
    packages:
        structure: '>=2.7.0'
        yform/manager: '>=2.3'
        yrewrite: '>=2.5'
