package: seoinspector
version: '0.3.1'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/seoinspector

requires:
    redaxo: '^5.2'
    packages:
        structure: '^2.0'
        yform/manager: '^2.0'
        yrewrite: '^2.2.1'
